### PR TITLE
Remove Azure backend

### PR DESCRIPTION
**Pull request by bensteinberg**
This undoes #2695. It is here for simplification, but is mainly a test to see if auto-assignment of reviewers is working.

### CODE REVIEW

**Comment by rebeccacremona** [comment]
@mcharters It's been a couple of years! Are you still running an instance of perma.cc that uses Azure storage? We are interested in dropping this dependency if it's not in use.

**Review by matteocargnelutti — APPROVED** [review]
PR looks good to me on the code front 😄 . 

Approving changes so they can be merged when / if this discussion item is resolved: https://github.com/harvard-lil/perma/pull/3104#issuecomment-1156890175

**Comment by mcharters** [comment]
> @mcharters It's been a couple of years! Are you still running an instance of perma.cc that uses Azure storage? We are interested in dropping this dependency if it's not in use.

Hi there! Yes, we are still using perma.cc and Azure storage. Happy to try and find a way to come up with an alternative solution if this dependency needs to be removed.

**Comment by bensteinberg** [comment]
Thanks, @mcharters  -- I'm closing this.

**Comment by bensteinberg** [comment]
@mcharters I just tried to upgrade a dependency and found that `azure-storage-blob` was holding it back, so I thought I'd check in with you again. Are you still running Perma? Are you still using the Azure storage backend?

**Comment by mcharters** [comment]
> @mcharters I just tried to upgrade a dependency and found that `azure-storage-blob` was holding it back, so I thought I'd check in with you again. Are you still running Perma? Are you still using the Azure storage backend?

Hi @bensteinberg - yes on both fronts, although admittedly I haven't updated our version of Perma in some time. It wasn't too much to add it on my fork the last time, so if you do need to delete it go ahead and I can try adding it back when the time comes to update our fork?

**Comment by bensteinberg** [comment]
Thanks! Let me try it out, and if it gets me past the dependency problem I'll make a new PR -- I'll let you know, if so.

**Pull request closed without merging**
