### PR TITLE
Create page: First round of redesign

### PR DESCRIPTION
**Pull request by thisisdano**
This bit of redesign sets the state for the bigger changes that will come later.

- Closes carousel bugs
- Updates create page to perform well across device widths
- Updates the styles for the modal uploader, uses js to calculate its centered position on the screen
- Introduces the "yellow flash" animation for an important message (we'll see this again on the new Record page)
- Updates spinner
- Changes animation style from slideDown to fadeIn

### CODE REVIEW

**Comment by thisisdano** [comment]
Looks like changes to the html on the page is throwing an error. MP, can you help me figure out the best fix?

**Comment by thisisdano** [comment]
Looks like it could just be a matter of modifying the line in test.py from
`assert_text_displayed('Create a Perma archive', 'h3')  # wait for load` 
to
`assert_text_displayed('Create a new Perma Link', 'h3')  # wait for load`

But I'll wait for more info...

**Comment by phillipsm** [comment]
Yup. I think that's right, @thisisdano. Update those tests and then run `fab test`.

Run I'm jetting for a for a few days. @jcushman's the local master at this. I'm happy to take a pass when I get back too.

**Comment by thisisdano** [comment]
OH SNAP IT WORKED

**Pull request merged**
