### PR TITLE
Dow styles record

### PR DESCRIPTION
**Pull request by thisisdano**
New Record page — preliminary pass. 
Still needs work on actions, status, privacy, tray metadata.

### CODE REVIEW

**Comment by thisisdano** [comment]
All kinds of errors in here. Ackkkkkk

**Comment by jcushman** [comment]
There's a bunch of junk in the log, but the only actual error is `Unable to find element with xpath '//a[contains(text(),'View the live page')]`. Maybe that language changed?

**Comment by thisisdano** [comment]
OK, good to know — that language is wrapped in a <span> inside the <a>, so I'll just switch it to a different <a>'s content.

**Comment by thisisdano** [comment]
Eff. Failed again.....

**Comment by thisisdano** [comment]
I'm gonna close this PR and merge it into my next big one.

**Pull request closed without merging**
