### PR TITLE
Show capture progress in button.

### PR DESCRIPTION
**Pull request by jcushman**
This is what's currently running on perma-test ...

### CODE REVIEW

**Comment by phillipsm** [comment]
The status updates are cool. I like seeing them as a pro user with behind the scenes knowledge. My gut reaction though is that the user won't *get it* and that it'll lead to confusion. Best to keep it simple.

Would love to get @cdemarco's, @anniejocain's, @abziegler's, and @thisisdano's take.

**Comment by thisisdano** [comment]
I'm curious to see it... I like the idea of seeing progress, but maybe not at the expense of clarity.

**Comment by jcushman** [comment]
You can see a demo of this idea at https://perma-test.law.harvard.edu/manage/create . Maybe we should show it at the Perma meeting and kick it around. The motivation here is that we now make people wait up to a minute longer before seeing any kind of positive feedback that their capture is working, which is like infinity in internet time -- hard to smooth over with just a spinner. Curious to kick around solutions for that.

**Comment by jcushman** [comment]
A nice middle ground that Matt mentioned before might be a progress bar, tied to the same capture steps I'm showing now in this demo. For a geeky easter egg we could throw in the actual capture steps as a tooltip.

**Comment by thisisdano** [comment]
I kinda like the changing update message. We should think about the language -- communicating progress in addition to state. maybe even better when combined with progress bar?

**Comment by anniejocain** [comment]
I think it could work. Another idea would be to just say 'step 1 of 5' either with or without a simplified description

**Comment by phillipsm** [comment]
Let's freshen this up. Maybe we sketch it out with @jcushman and @anastasia ?

**Comment by phillipsm** [comment]
Let's rework this back in. Maybe get @anastasia's take. Or, let's close this. (I think we should adjust a little and merge it in.)

**Comment by anastasia** [comment]
Assigning this to me because apparently I've been missing this conversation

**Pull request closed without merging**
