### PR TITLE
Infinite scroll and footer access

### PR DESCRIPTION
**Pull request by rebeccacremona**
This is a first pass at https://github.com/harvard-lil/perma/issues/1218.

The styles look good on my browsers, but zoom settings are interfering somewhat with testing: I _think_ it's legitimately fine (at any standard zoom), but am not positive.

Scroll bars should appear when the content is too long, and not appear when the content fits. Folders and Links scroll separately. The Folders section heading with its important button, does not scroll. A subtle shadow should keep the Links list from looking peculiar during scrolling. Scroll bars should not bump other content out of the way. The Folders list should be horizontally scrollable, but the horizontal scroll bar should not appear. 

No scrolling:
image

Scrollable links, at the top:
image

Scrolling through links:
image

Scrolling folders and links at the same time:
image

### CODE REVIEW

**Comment by rebeccacremona** [comment]
WHOA! And, evidently, those scroll bars only show up all the time, at least on Apple devices, if you are a weirdo like me and have your preferences configured accordingly. For other people, the scroll bars show up only while you are scrolling.

How do you people know when there is more content to see, if you don't have a scroll bar?

image

**Comment by anastasia** [comment]
This looks really great, both code-wise and locally in browser. I'm so happy it's happening, it makes Perma much more friendly to users. 
One question and also the tiniest of nitpicks that you're welcome to ignore:
- You treat the Folders header and the Your Perma Links header differently — one is excluded from scroll and one is included in it. I'm assuming that you do that because the Folders header has important buttons in it, like you said in the description, but wondering if you think it might be worthwhile to treat the headers the same way for clarity? 
- The nitpick is there are function-scoped `var`s that can be declared using `let`s (`scrollIfTallerThanFractionOfViewport`, `markIfScrolled`).

**Comment by rebeccacremona** [comment]
Thx! I will change the `var` declarations in the folder-tree to `let`s.

Re: the headers, yeah, I was wondering about that and tried it both ways. Since the search bar is so big, and since there aren't any buttons in the Link section, I personally liked it better this way: more links visible at a time seemed like a win. I also realized at one point that very few people are going to be scrolling folders anyway: I think with very few exceptions, only admins will run into so long a list of folders. Do you feel strongly about it (fine if you do!)? 

FWIW I hate this whole thing and think it should be paginated instead lol.

**Comment by anastasia** [comment]
(I'm pro pagination as well) No I don't feel strongly enough about any of it to fight for it. Let's keep it!

**Comment by rebeccacremona** [comment]
Done!

**Pull request merged**
