### PR TITLE
Django 1.10

### PR DESCRIPTION
**Pull request by jcushman**
I think it's time.

### CODE REVIEW

**Comment by rebeccacremona** [comment]
Looks good to me too!! Except for one thing: for logging to work the way it used to, locally, for people like me (who use local log files), we need to add this to settings_dev.py
```
# per https://docs.djangoproject.com/en/1.11/releases/1.10/#runserver-output-goes-through-logging
LOGGING['formatters']['django.server'] = {
    '()': 'django.utils.log.ServerFormatter',
    'format': '[%(server_time)s] %(message)s',
}
LOGGING['handlers']['django.server'] = {
    'level': 'INFO',
    'class': 'logging.StreamHandler',
    'formatter': 'django.server',
}
LOGGING['loggers']['django.server'] = {
    'handlers': ['django.server'],
    'level': 'INFO',
    'propagate': False,
}
```

**Comment by rebeccacremona** [comment]
Should that be part of the repo, or should I just add it to my settings.py? I'm probably the only one using local log files.

**Comment by jcushman** [comment]
What does using local log files mean? Are you adding a setting to settings.py that breaks under 1.10? I'd be curious to see it -- could make sense to pull stuff into settings_dev.py if you're finding it helpful.

**Comment by rebeccacremona** [comment]
With 1.9, I sometimes run with `LOGGING['handlers']['default']['filters'] = []` in settings.py, so that I have a record of stack traces that are happening during capture inside /perma-rlc/services/logs/django.log, so I can more easily look for commonalities, and so I can see a log a little closer to our production log than what prints to the terminal. They are pretty verbose, so you have to clean up every so often. That breaks with 1.10, as per their release notes. I can get the same behavior using:
```
LOGGING['handlers']['default']['filters'] = []
# per https://docs.djangoproject.com/en/1.11/releases/1.10/#runserver-output-goes-through-logging
LOGGING['formatters']['django.server'] = {
    '()': 'django.utils.log.ServerFormatter',
    'format': '[%(server_time)s] %(message)s',
}
LOGGING['handlers']['django.server'] = {
    'level': 'INFO',
    'class': 'logging.StreamHandler',
    'formatter': 'django.server',
}
LOGGING['loggers']['django.server'] = {
    'handlers': ['django.server'],
    'level': 'INFO',
    'propagate': False,
}
```

**Pull request merged**
