### PR TITLE
Let a user indicate that the image capture is preferred to the web capture

### PR DESCRIPTION
**Pull request by kilbergr**
Ok so! This PR addresses [this open issue](https://github.com/harvard-lil/perma/issues/1470) to "Let a user indicate that the image capture is preferred to the web capture".

The PR adds a boolean field to the `perma_link` object called `screenshot_view`. When it's true, the URL (i.e. https://perma.cc/5WFL-AJ27) without any type specified defaults to displaying a screenshot view if the screenshot is present. If the screenshot is not present, the capture will be shown. When `screenshot_view` field is false, the opposite is true.

When a user specifies image type, (i.e. https://perma.cc/5WFL-AJ27?type=image), the screenshot, if present, will be shown regardless of `screenshot_view` value. This PR introduces a `standard` type (i.e. https://perma.cc/5WFL-AJ27?type=standard) for user to specify viewing the capture instead of the screenshot.

A minor aesthetic change: when the `Show record details` dropdown is displayed, the `Screenshot` `Standard` View Mode options are no longer visible.

### CODE REVIEW

**Review by bensteinberg — APPROVED** [review]
LGTM, but I have added @rebeccacremona as a reviewer and will defer to her.

**Review by rebeccacremona — CHANGES_REQUESTED** [review]
We chatted about a few suggested changes offline; will re-review when ready!

**Comment by kilbergr** [comment]
Hoorah passing and all comments addressed ! @rebeccacremona ready for a fresh look when you have the chance.

**Review by rebeccacremona — APPROVED** [review]
This looks great 🎉 !!!

**Comment by rebeccacremona** [comment]
I saw a tiny rendering problem with the expandable link list on Firefox and Chrome that didn't show up in Safari (😅), so took the liberty of pushing up a couple of lines of css for that:

image

While messing with that, happened to notice that the two radio buttons there had the same ID's, so clicking on the "screenshot" label filled in the "standard" button, so just went ahead and updated that as well.

Congrats, @kilbergr at landing a feature Perma users have been wanting forever! Folks are going to be so jazzed. Can't wait until this is publicized.

**Pull request merged**
